/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-container-low": "#f4f4f4",
        "surface": "#ffffff",
        "on-secondary-fixed": "#161616",
        "on-background": "#161616",
        "tertiary-container": "#a7f0ba",
        "on-primary-fixed": "#001d6c",
        "background": "#ffffff",
        "outline-variant": "#e0e0e0",
        "outline": "#8d8d8d",
        "on-primary-container": "#161616",
        "inverse-primary": "#78a9ff",
        "surface-dim": "#e0e0e0",
        "inverse-surface": "#393939",
        "secondary-fixed": "#e0e0e0",
        "tertiary-fixed-dim": "#42be65",
        "primary-fixed-dim": "#78a9ff",
        "on-surface": "#161616",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error-container": "#750e13",
        "secondary": "#6f6f6f",
        "primary": "#0f62fe",
        "on-primary": "#ffffff",
        "error": "#da1e28",
        "surface-tint": "#0f62fe",
        "surface-container-high": "#e0e0e0",
        "primary-container": "#d0e2ff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#a7f0ba",
        "surface-container-highest": "#c6c6c6",
        "on-surface-variant": "#525252",
        "on-secondary-fixed-variant": "#525252",
        "secondary-fixed-dim": "#c6c6c6",
        "secondary-container": "#e0e0e0",
        "on-tertiary-container": "#044317",
        "on-tertiary-fixed-variant": "#044317",
        "surface-variant": "#f4f4f4",
        "inverse-on-surface": "#f4f4f4",
        "on-secondary-container": "#525252",
        "error-container": "#fff1f1",
        "tertiary": "#198038",
        "surface-bright": "#ffffff",
        "on-primary-fixed-variant": "#0043ce",
        "on-tertiary-fixed": "#022d0d",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d0e2ff",
        "surface-container": "#f4f4f4"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["IBM Plex Sans"],
        "display": ["IBM Plex Sans"],
        "body": ["IBM Plex Sans"],
        "label": ["IBM Plex Sans"]
      }
    },
  },
  plugins: [],
}
